@baseUri = http://localhost:8000
@contentType = application/json

########
GET {{baseUri}}/admins?skip=0 HTTP/1.1

########
POST {{baseUri}}/admins HTTP/1.1
Content-Type: {{contentType}}

{
    "firstName": "John",
    "lastName": "Doe",
    "username": "admin",
    "password": "admin",
    "confirmPassword": "admin"
}

########
PATCH {{baseUri}}/admins/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "id": 1,
    "firstName": "Nick",
    "lastName": "Jackson",
    "username": "nickjang"
}