@baseUri = http://localhost:8000
@contentType = application/json

########
GET {{baseUri}}/employees?skip=0 HTTP/1.1

########
POST {{baseUri}}/employees HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiTmljayIsImxhc3ROYW1lIjoiSmFja3NvbiIsInVzZXJuYW1lIjoibmlja2phY2tzb24iLCJjcmVhdGVkQXQiOiIyMDIyLTA4LTI4VDAwOjIwOjQ1LjIyOFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTA4LTI4VDAwOjIwOjQ1LjIyOFoiLCJkZWxldGVkQXQiOm51bGwsImlhdCI6MTY2MTY1NDE4MH0.Tb7fRAOI430FEZmhfducsWSA7ta6HOKVOKWAIMjmDyo

{
    "firstName": "John",
    "lastName": "Doe"
}

########
PATCH {{baseUri}}/employees/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "firstName": "John",
    "lastName": "Doe"
}